-- @description SK Drums Generator
-- @author Studio Kozak
-- @version 2.2
-- @provides [main] .
-- @about
--   A 16-step drum pattern sequencer that writes MIDI items into REAPER.
--
--   Eight drum elements, each with its own MIDI note and name, over up to as
--   many bars as needed. Every step carries one of five velocity layers, from
--   ghost note to fortissimo. Patterns can be drawn by hand, pulled from twenty
--   factory styles, or generated by a randomiser that follows common drumming
--   conventions. Swing, timing and velocity spread add human feel, and an
--   optional fill can close the eighth bar.
--
--   Your own patterns can be saved, reloaded and deleted, and exported to the
--   clipboard as ready-to-paste code.
--
--   Point it at a track carrying a drum sampler, set the note numbers to match
--   the sampler's pads, then click GENERATE & REPLACE.
--
--   Requires the ReaImGui extension. The SWS extension is needed only for the
--   clipboard export.

local reaper = reaper

if not reaper.ImGui_CreateContext then
  reaper.MB("ReaImGui is required. Please install it via ReaPack.", "Missing dependency", 0)
  return
end

-------------------------------------------------------------------------------
-- Drum elements
-------------------------------------------------------------------------------

local DRUM_MAP = {
  { id = "kick",         name = "KICK",  note = 36, color = 0xFF4444FF },
  { id = "snare",        name = "SNARE", note = 37, color = 0x44FF44FF },
  { id = "hihat_closed", name = "H.HAT", note = 38, color = 0x4444FFFF },
  { id = "hihat_open",   name = "OPEN",  note = 39, color = 0xFFFF44FF },
  { id = "clap",         name = "CLAP",  note = 47, color = 0xFF8844FF },
  { id = "rimshot",      name = "RIM",   note = 51, color = 0x88FF44FF },
  { id = "tom_high",     name = "T.HI",  note = 43, color = 0x44FFFFFF },
  { id = "tom_low",      name = "T.LO",  note = 41, color = 0xAA44FFFF },
}

local DEFAULT_NOTES = { 36, 37, 38, 39, 47, 51, 43, 41 }
local DEFAULT_NAMES = { "KICK", "SNARE", "H.HAT", "OPEN", "CLAP", "RIM", "T.HI", "T.LO" }

-------------------------------------------------------------------------------
-- Note and name assignment, remembered between sessions
-------------------------------------------------------------------------------

local EXT_SECTION = "Studio Kozak Drums Generator"

local NAME_MAX = 10

local function sanitize_name(s)
  s = tostring(s or ""):gsub("[%c,]", ""):gsub("^%s+", ""):gsub("%s+$", "")
  if s == "" then return nil end
  return s:sub(1, NAME_MAX)
end

local function save_mapping()
  for _, inst in ipairs(DRUM_MAP) do
    reaper.SetExtState(EXT_SECTION, "note_" .. inst.id, tostring(inst.note), true)
    reaper.SetExtState(EXT_SECTION, "name_" .. inst.id, inst.name, true)
  end
end

local function load_mapping()
  for i, inst in ipairs(DRUM_MAP) do
    local raw = reaper.GetExtState(EXT_SECTION, "note_" .. inst.id)
    local n   = tonumber(raw)
    if n and n >= 0 and n <= 127 then DRUM_MAP[i].note = n end
    local nm = sanitize_name(reaper.GetExtState(EXT_SECTION, "name_" .. inst.id))
    if nm then DRUM_MAP[i].name = nm end
  end
end

local function reset_mapping()
  for i in ipairs(DRUM_MAP) do
    DRUM_MAP[i].note = DEFAULT_NOTES[i]
    DRUM_MAP[i].name = DEFAULT_NAMES[i]
  end
  save_mapping()
end

load_mapping()

-------------------------------------------------------------------------------
-- Velocity layers
--
--  0  OFF      silent step
--  1  GHOST    20-40     ghost notes, brush sweeps
--  2  SOFT     50-70     light filler hits
--  3  NORM     80-100    standard playing
--  4  ACCENT   105-115   accents
--  5  FFFF     118-127   downbeats, crash hits
-------------------------------------------------------------------------------

local VEL_LAYERS = {
  [0] = { label = "OFF",    min = 0,   max = 0   },
  [1] = { label = "GHOST",  min = 20,  max = 40  },
  [2] = { label = "SOFT",   min = 50,  max = 70  },
  [3] = { label = "NORM",   min = 80,  max = 100 },
  [4] = { label = "ACCENT", min = 105, max = 115 },
  [5] = { label = "FFFF",   min = 118, max = 127 },
}

-- Step colours. The legend under the grid reads this same table.
local VEL_COLORS = {
  [0] = nil,
  [1] = 0x4444AAFF,
  [2] = 0x4488AAFF,
  [3] = 0x44FF44FF,
  [4] = 0xFF8800FF,
  [5] = 0xFF2222FF,
}

local function to_layer(v)
  if v == true  then return 3 end
  if v == false then return 0 end
  if type(v) == "number" then return math.max(0, math.min(5, math.floor(v))) end
  return 0
end

local function vel_from_layer(layer, h_v)
  local L = VEL_LAYERS[layer]
  if not L or L.min == 0 then return 0 end
  return math.max(1, math.min(127,
    math.random(L.min, L.max) + math.random(-h_v, h_v)))
end

-------------------------------------------------------------------------------
-- Pattern state
-------------------------------------------------------------------------------

local grid = {}

local function init_grid(total_steps, clear_all)
  if clear_all then grid = {} end
  for i = 1, #DRUM_MAP do
    if not grid[i] then grid[i] = {} end
    for s = 1, total_steps do
      if clear_all or grid[i][s] == nil then grid[i][s] = 0 end
    end
  end
end

local function set(inst, step, layer)
  grid[inst][step] = to_layer(layer == nil and true or layer)
end

-------------------------------------------------------------------------------
-- Randomiser
-------------------------------------------------------------------------------

local function randomize_intelligent(page_start, page_end)
  math.randomseed(os.time() + reaper.time_precise() * 100000)
  for p = page_start, page_end do
    for s = 1, 16 do
      local step = (p * 16) + s
      for i = 1, #DRUM_MAP do grid[i][step] = 0 end
    end

    -- Kick
    local kick_density   = math.random(2, 5)
    local kick_positions = {}
    if math.random() > 0.1 then table.insert(kick_positions, 1) end
    local possible_kicks = { 3, 5, 7, 9, 10, 11, 13, 14, 15 }
    local iter = 0
    while #kick_positions < kick_density and iter < 100 do
      iter = iter + 1
      local pos    = possible_kicks[math.random(#possible_kicks)]
      local exists = false
      for _, v in ipairs(kick_positions) do if v == pos then exists = true break end end
      if not exists then table.insert(kick_positions, pos) end
    end
    for _, pos in ipairs(kick_positions) do
      grid[1][(p*16)+pos] = (pos == 1) and 5 or (math.random() > 0.4 and 4 or 3)
    end

    -- Snare
    if math.random() > 0.05 then
      grid[2][(p*16)+5]  = 4
      grid[2][(p*16)+13] = 4
    end
    if math.random() > 0.8 then
      local gp = { 3, 7, 11, 15 }
      for _ = 1, math.random(1, 2) do
        grid[2][(p*16) + gp[math.random(#gp)]] = 1
      end
    end

    -- Hi-hat
    local hat_mode = math.random(1, 4)
    if hat_mode == 1 then
      for s = 1, 16, 2 do
        if math.random() > 0.1 then
          grid[3][(p*16)+s] = (s%4==1) and 3 or 2
        end
      end
    elseif hat_mode == 2 then
      for s = 1, 16 do
        if math.random() > 0.2 then
          grid[3][(p*16)+s] = (s%4==1) and 4 or (s%2==0) and 1 or 2
        end
      end
    elseif hat_mode == 3 then
      for s = 1, 16, 4 do grid[3][(p*16)+s] = 3 end
    else
      for s = 1, 16 do
        if s%2==1 or math.random()>0.6 then
          grid[3][(p*16)+s] = math.random()>0.7 and 4 or 2
        end
      end
    end

    -- Open hat
    if math.random() > 0.5 then
      local candidates = { 4, 8, 12, 16 }
      local placed = {}
      for _ = 1, math.random(1, 3) do
        local pos    = candidates[math.random(#candidates)]
        local exists = false
        for _, v in ipairs(placed) do if v == pos then exists = true break end end
        if not exists then
          table.insert(placed, pos)
          grid[4][(p*16)+pos] = 3
          grid[3][(p*16)+pos] = 0
        end
      end
    end

    -- Clap / Rimshot / Toms
    if math.random() > 0.7 then
      grid[5][(p*16)+5]  = 4
      grid[5][(p*16)+13] = 4
    end
    if math.random() > 0.6 then
      for _ = 1, math.random(1, 4) do
        local pos = math.random(1, 16)
        if pos ~= 5 and pos ~= 13 then grid[6][(p*16)+pos] = 2 end
      end
    end
    if math.random() > 0.95 then grid[7][(p*16)+math.random(1,16)] = 4 end
    if math.random() > 0.97 then grid[8][(p*16)+math.random(1,16)] = 4 end
  end
end

-------------------------------------------------------------------------------
-- Factory patterns
-------------------------------------------------------------------------------

local FACTORY_PRESETS = {
  { name = "--- EMPTY ---",
    func = function(gs) init_grid(gs, true) end },
  { name = "Hip-Hop — Dilla Soul",
    func = function(gs) init_grid(gs,true) for s=1,gs,16 do set(1,s,5) set(1,s+10,4) set(2,s+4,4) set(2,s+12,4) set(3,s,3) set(3,s+2,2) set(3,s+4,3) set(3,s+6,2) set(3,s+9,1) set(3,s+11,2) set(3,s+13,2) set(3,s+15,1) end end },
  { name = "Trap — Dark Drill",
    func = function(gs) init_grid(gs,true) for s=1,gs,16 do set(1,s,5) set(1,s+10,4) set(2,s+8,4) for h=1,16,3 do set(3,s+h-1,2) end set(3,s+11,3) set(3,s+12,2) end end },
  { name = "Rock — Ghost Notes",
    func = function(gs) init_grid(gs,true) for s=1,gs,16 do set(1,s,5) set(1,s+6,4) set(1,s+9,3) set(2,s+4,5) set(2,s+12,5) set(2,s+7,1) set(2,s+10,1) for h=1,16,2 do set(3,s+h-1,3) end end end },
  { name = "Trip-Hop — Bristol Groove",
    func = function(gs) init_grid(gs,true) for s=1,gs,16 do set(1,s,5) set(1,s+2,3) set(1,s+11,4) set(2,s+5,4) set(2,s+13,4) set(4,s+7,3) set(4,s+15,3) end end },
  { name = "Electro — Industrial",
    func = function(gs) init_grid(gs,true) for s=1,gs,4 do set(1,s,5) end for s=1,gs,16 do set(6,s+3,4) set(6,s+7,4) set(6,s+11,4) set(6,s+15,5) set(5,s+4,4) set(5,s+12,4) end end },
  { name = "Afrobeat — Lagos",
    func = function(gs) init_grid(gs,true) for s=1,gs,16 do set(1,s,5) set(1,s+6,4) set(1,s+10,3) set(6,s+2,3) set(6,s+5,2) set(6,s+8,3) set(6,s+13,2) set(3,s,3) set(3,s+4,3) set(3,s+8,3) set(3,s+12,3) end end },
  { name = "Phonk — Drift",
    func = function(gs) init_grid(gs,true) for s=1,gs,16 do set(1,s,5) set(1,s+6,4) set(1,s+8,4) set(1,s+14,3) set(5,s+4,4) set(5,s+12,4) for h=1,16 do set(3,s+h-1,2) end end end },
  { name = "Funk — Linear Break",
    func = function(gs) init_grid(gs,true) for s=1,gs,16 do set(1,s,5) set(2,s+3,2) set(3,s+4,3) set(1,s+6,4) set(2,s+9,1) set(3,s+11,2) set(1,s+12,3) set(2,s+14,4) end end },
  { name = "UK Garage — 2-Step",
    func = function(gs) init_grid(gs,true) for s=1,gs,16 do set(1,s,5) set(1,s+10,4) set(2,s+4,4) set(2,s+12,4) set(4,s+2,3) set(4,s+6,3) set(4,s+11,3) set(4,s+14,3) end end },
  { name = "Drum & Bass — Amen Style",
    func = function(gs) init_grid(gs,true) for s=1,gs,16 do set(1,s,5) set(1,s+10,4) set(2,s+4,5) set(2,s+12,5) set(2,s+15,3) for h=1,16,2 do set(3,s+h-1,3) end set(3,s+10,2) end end },
  { name = "Jazz — Ride Swing",
    func = function(gs) init_grid(gs,true) for s=1,gs,16 do set(3,s,3) set(3,s+2,4) set(3,s+4,3) set(3,s+6,4) set(3,s+8,3) set(3,s+10,4) set(3,s+12,3) set(3,s+14,4) set(2,s+2,1) set(2,s+4,2) set(2,s+6,1) set(2,s+9,1) set(2,s+12,2) set(2,s+14,1) set(1,s,4) set(1,s+6,2) set(1,s+14,2) set(4,s+4,3) set(4,s+12,3) end end },
  { name = "Jazz — Brushes Ballad",
    func = function(gs) init_grid(gs,true) for s=1,gs,16 do for h=1,16 do if h%3~=0 then set(2,s+h-1,1) end end set(2,s,2) set(2,s+4,2) set(2,s+8,2) set(2,s+12,2) set(3,s,3) set(3,s+8,3) set(1,s,3) end end },
  { name = "Jazz — Latin Swing",
    func = function(gs) init_grid(gs,true) for s=1,gs,16 do set(6,s,5) set(6,s+3,4) set(6,s+6,4) set(6,s+8,5) set(6,s+12,4) for h=1,16,2 do set(3,s+h-1,3) end set(3,s+2,4) set(3,s+10,4) set(2,s+5,1) set(2,s+9,2) set(2,s+13,1) set(1,s,5) set(1,s+8,4) end end },
  { name = "Bossa Nova — Classic",
    func = function(gs) init_grid(gs,true) for s=1,gs,16 do set(6,s+1,5) set(6,s+4,5) set(6,s+7,4) set(6,s+9,5) set(6,s+12,4) set(4,s,2) set(4,s+4,2) set(4,s+8,2) set(4,s+12,2) set(2,s+4,2) set(2,s+12,2) set(1,s,3) set(1,s+8,2) end end },
  { name = "Bossa Nova — Batucada",
    func = function(gs) init_grid(gs,true) for s=1,gs,16 do set(6,s,4) set(6,s+3,3) set(6,s+6,4) set(6,s+8,5) set(6,s+11,3) set(6,s+13,4) for h=1,16 do set(3,s+h-1,2) end set(3,s,3) set(3,s+4,3) set(3,s+8,3) set(3,s+12,3) set(7,s+2,3) set(7,s+6,4) set(7,s+10,3) set(7,s+14,4) set(2,s+4,3) set(2,s+9,2) set(2,s+12,3) set(1,s,5) set(1,s+6,3) set(1,s+8,4) end end },
  { name = "Samba — Traditional",
    func = function(gs) init_grid(gs,true) for s=1,gs,16 do set(6,s,4) set(6,s+3,5) set(6,s+6,4) set(6,s+9,5) set(6,s+11,3) set(6,s+14,4) set(1,s,2) set(1,s+8,5) set(4,s,2) set(4,s+4,2) set(4,s+8,2) set(4,s+12,2) set(2,s,3) set(2,s+2,2) set(2,s+4,4) set(2,s+6,2) set(2,s+8,3) set(2,s+10,1) set(2,s+12,4) set(2,s+14,2) set(7,s+1,3) set(7,s+5,2) set(7,s+9,3) set(7,s+13,2) end end },
  { name = "Samba — Pagode Groove",
    func = function(gs) init_grid(gs,true) for s=1,gs,16 do set(1,s,4) set(1,s+3,3) set(1,s+8,5) set(1,s+10,3) set(1,s+13,2) set(2,s+1,1) set(2,s+3,1) set(2,s+4,4) set(2,s+7,1) set(2,s+9,1) set(2,s+11,1) set(2,s+12,4) set(2,s+14,2) for h=1,16,2 do set(3,s+h-1,2) end set(3,s,3) set(3,s+8,3) set(6,s+2,4) set(6,s+6,5) set(6,s+10,4) set(6,s+14,5) set(8,s+4,3) set(8,s+12,3) end end },
  { name = "Afro-Cuban — Son Clave",
    func = function(gs) init_grid(gs,true) for s=1,gs,16 do set(6,s,5) set(6,s+3,5) set(6,s+6,5) set(6,s+8,5) set(6,s+12,5) set(1,s+2,3) set(1,s+7,4) set(1,s+10,3) set(1,s+15,4) set(2,s+4,3) set(2,s+8,2) set(2,s+12,4) for h=1,16,2 do set(3,s+h-1,3) end set(4,s+7,4) set(4,s+15,4) set(5,s+3,3) set(5,s+11,3) end end },
  { name = "Afro-Cuban — Rumba",
    func = function(gs) init_grid(gs,true) for s=1,gs,16 do set(6,s,5) set(6,s+3,5) set(6,s+7,5) set(6,s+8,5) set(6,s+12,5) set(1,s,4) set(1,s+6,3) set(1,s+11,4) set(2,s+2,2) set(2,s+5,3) set(2,s+9,2) set(2,s+13,3) set(7,s+1,3) set(7,s+4,4) set(7,s+8,3) set(7,s+12,4) set(8,s+3,3) set(8,s+7,4) set(8,s+11,3) set(8,s+15,4) set(4,s+4,2) set(4,s+12,2) end end },
}

-------------------------------------------------------------------------------
-- User patterns
--
--  Saved patterns survive between sessions. Each one keeps its bar count and
--  its groove settings alongside the steps, so loading one restores the
--  pattern exactly as it was saved.
-------------------------------------------------------------------------------

local user_presets = {}

local function serialize_grid(bars)
  local parts = {}
  local total = bars * 16
  for i = 1, #DRUM_MAP do
    for s = 1, total do
      parts[#parts + 1] = tostring(grid[i][s] or 0)
    end
  end
  return table.concat(parts, ",")
end

local function deserialize_grid(data, bars)
  local total  = bars * 16
  local values = {}
  for v in data:gmatch("[^,]+") do values[#values + 1] = tonumber(v) or 0 end
  local idx = 1
  for i = 1, #DRUM_MAP do
    grid[i] = {}
    for s = 1, total do
      grid[i][s] = values[idx] or 0
      idx = idx + 1
    end
  end
end

-- Groove settings travel with a pattern, stored as "swing,timing,spread".
local function groove_to_string(g)
  return string.format("%d,%d,%d", g.swing or 0, g.h_t or 0, g.h_v or 0)
end

local function groove_from_string(s)
  if not s or s == "" then return nil end
  local a, b, c = s:match("^(%-?%d+),(%-?%d+),(%-?%d+)$")
  if not a then return nil end
  local function clamp(v, lo, hi) return math.max(lo, math.min(hi, tonumber(v))) end
  return { swing = clamp(a, 0, 100), h_t = clamp(b, 0, 100), h_v = clamp(c, 0, 80) }
end

local function save_user_presets()
  reaper.SetExtState(EXT_SECTION, "user_preset_count",
    tostring(#user_presets), true)
  for i, p in ipairs(user_presets) do
    reaper.SetExtState(EXT_SECTION, "user_preset_name_" .. i, p.name,  true)
    reaper.SetExtState(EXT_SECTION, "user_preset_bars_" .. i,
      tostring(p.bars), true)
    reaper.SetExtState(EXT_SECTION, "user_preset_data_" .. i, p.data,  true)
    if p.groove then
      reaper.SetExtState(EXT_SECTION, "user_preset_groove_" .. i,
        groove_to_string(p.groove), true)
    else
      reaper.DeleteExtState(EXT_SECTION, "user_preset_groove_" .. i, true)
    end
  end
  -- Clear any leftover slots beyond the current count
  for i = #user_presets + 1, #user_presets + 10 do
    reaper.DeleteExtState(EXT_SECTION, "user_preset_name_" .. i, true)
    reaper.DeleteExtState(EXT_SECTION, "user_preset_bars_" .. i, true)
    reaper.DeleteExtState(EXT_SECTION, "user_preset_data_" .. i, true)
    reaper.DeleteExtState(EXT_SECTION, "user_preset_groove_" .. i, true)
  end
end

local function load_user_presets()
  user_presets = {}
  local count = tonumber(
    reaper.GetExtState(EXT_SECTION, "user_preset_count")) or 0
  for i = 1, count do
    local name = reaper.GetExtState(EXT_SECTION, "user_preset_name_" .. i)
    local bars = tonumber(
      reaper.GetExtState(EXT_SECTION, "user_preset_bars_" .. i)) or 1
    local data = reaper.GetExtState(EXT_SECTION, "user_preset_data_" .. i)
    -- A pattern with no groove stored yields nil here.
    local groove = groove_from_string(
      reaper.GetExtState(EXT_SECTION, "user_preset_groove_" .. i))
    if name ~= "" and data ~= "" then
      local captured_data = data
      local captured_bars = bars
      user_presets[#user_presets + 1] = {
        name = name,
        bars = captured_bars,
        data = captured_data,
        groove = groove,
        func = function(_gs)
          init_grid(captured_bars * 16, true)
          deserialize_grid(captured_data, captured_bars)
        end,
      }
    end
  end
end

local function save_current_as_user_preset(name, bars, groove)
  name = name:match("^%s*(.-)%s*$")  -- trim whitespace
  if name == "" then return false, "Name cannot be empty." end
  for _, p in ipairs(user_presets) do
    if p.name == name then return false, "A preset named '" .. name .. "' already exists." end
  end
  local data = serialize_grid(bars)
  local captured_data = data
  local captured_bars = bars
  user_presets[#user_presets + 1] = {
    name = name,
    bars = bars,
    data = data,
    groove = groove,
    func = function(_gs)
      init_grid(captured_bars * 16, true)
      deserialize_grid(captured_data, captured_bars)
    end,
  }
  save_user_presets()
  return true, "Preset '" .. name .. "' saved."
end

local function delete_user_preset(idx)
  if idx < 1 or idx > #user_presets then return end
  table.remove(user_presets, idx)
  save_user_presets()
end

-- Copies the pattern to the clipboard as code that can be pasted straight
-- into the factory pattern list above.
local function export_to_clipboard(preset_name, bars, groove)
  preset_name = preset_name:match("^%s*(.-)%s*$")
  if preset_name == "" then preset_name = "My Pattern" end

  -- One line per active step
  local lines = {}
  local total = bars * 16
  for i = 1, #DRUM_MAP do
    for s = 1, total do
      local layer = to_layer(grid[i][s])
      if layer > 0 then
        lines[#lines + 1] = string.format("    set(%d, %d, %d)", i, s, layer)
      end
    end
  end

  -- Wrap it as a pattern entry
  local block = {}
  block[#block+1] = "  -- ======================================================"
  block[#block+1] = "  -- USER PRESET : " .. preset_name
  block[#block+1] = "  -- Bars   : " .. bars
  block[#block+1] = "  -- Saved  : " .. os.date("%Y-%m-%d %H:%M")
  block[#block+1] = "  -- ======================================================"
  block[#block+1] = "  { name = \"" .. preset_name .. "\","
  if groove then
    block[#block+1] = string.format(
      "    groove = { swing = %d, h_t = %d, h_v = %d },",
      groove.swing or 0, groove.h_t or 0, groove.h_v or 0)
  end
  block[#block+1] = "    func = function(gs)"
  block[#block+1] = "      init_grid(gs, true)"
  if #lines > 0 then
    for _, l in ipairs(lines) do block[#block+1] = l end
  else
    block[#block+1] = "      -- (empty pattern)"
  end
  block[#block+1] = "    end },"

  local result = table.concat(block, "\n")
  if not reaper.CF_SetClipboard then
    return nil, "The SWS extension is required to copy to the clipboard."
  end
  reaper.CF_SetClipboard(result)
  return result
end

load_user_presets()

-------------------------------------------------------------------------------
-- Target track
--
--  The track a pattern was written to is remembered for each project, so
--  generating still works after clicking elsewhere in REAPER. Items written
--  here are marked, which is how a regenerated pattern replaces the previous
--  one rather than piling on top of it.
-------------------------------------------------------------------------------

local PROJEXT  = "SK_DRUMS_GEN"
local ITEM_TAG = "P_EXT:SK_DRUMS_GEN"

local target_cache = { guid = nil, track = nil }

local function track_name(tr)
  local _, nm = reaper.GetSetMediaTrackInfo_String(tr, "P_NAME", "", false)
  if not nm or nm == "" then
    nm = "Track " .. math.floor(reaper.GetMediaTrackInfo_Value(tr, "IP_TRACKNUMBER"))
  end
  return nm
end

local function remember_track(tr)
  if not tr then return end
  local guid = reaper.GetTrackGUID(tr)
  target_cache.guid, target_cache.track = guid, tr
  reaper.SetProjExtState(0, PROJEXT, "last_track_guid", guid)
end

local function find_track_by_guid(guid)
  if not guid or guid == "" then return nil end
  for i = 0, reaper.CountTracks(0) - 1 do
    local tr = reaper.GetTrack(0, i)
    if reaper.GetTrackGUID(tr) == guid then return tr end
  end
  return nil
end

-- The remembered track of the current project, or nil if it was deleted.
local function remembered_track()
  local _, guid = reaper.GetProjExtState(0, PROJEXT, "last_track_guid")
  if not guid or guid == "" then return nil end
  local c = target_cache
  if c.guid == guid and c.track
     and reaper.ValidatePtr2(0, c.track, "MediaTrack*")
     and reaper.GetTrackGUID(c.track) == guid then
    return c.track
  end
  local tr = find_track_by_guid(guid)
  c.guid, c.track = guid, tr
  return tr
end

-- The track selected in REAPER, or failing that the remembered one.
local function target_track()
  local sel = reaper.GetSelectedTrack(0, 0)
  if sel then return sel, "selection" end
  local tr = remembered_track()
  if tr then return tr, "memory" end
  return nil, nil
end

-------------------------------------------------------------------------------
-- Autosave
--
--  The pattern being worked on is kept with the project, so closing the window
--  does not throw it away. It is written only when something actually changed,
--  and at most every couple of seconds, so simply opening the script and
--  looking around leaves the project untouched.
-------------------------------------------------------------------------------

local AUTOSAVE_KEY    = "last_state"
local AUTOSAVE_PERIOD = 2.0

local autosave_written = nil   -- last payload stored, to skip pointless writes
local autosave_checked = 0

-- "1;bars;swing,timing,spread;fill;steps"  (version first, so a later format
-- can be told apart from this one and simply ignored rather than misread)
local function state_to_string(st)
  return table.concat({
    "1",
    tostring(st.bars),
    groove_to_string(st),
    st.use_fill and "1" or "0",
    serialize_grid(st.bars),
  }, ";")
end

local function autosave(st, force)
  local now = reaper.time_precise()
  if not force and (now - autosave_checked) < AUTOSAVE_PERIOD then return end
  autosave_checked = now
  local payload = state_to_string(st)
  if payload == autosave_written then return end
  autosave_written = payload
  reaper.SetProjExtState(0, PROJEXT, AUTOSAVE_KEY, payload)
end

-- Restores the pattern saved with this project. Returns false when there is
-- nothing to restore, or when what is there cannot be read.
local function autoload(st)
  local _, payload = reaper.GetProjExtState(0, PROJEXT, AUTOSAVE_KEY)
  if not payload or payload == "" then return false end

  local ver, bars, groove, fill, data =
    payload:match("^(%d+);(%d+);([^;]*);([01]);(.*)$")
  if ver ~= "1" then return false end
  bars = tonumber(bars)
  if not bars or bars < 1 or data == "" then return false end

  st.bars = bars
  init_grid(bars * 16, true)
  deserialize_grid(data, bars)
  local g = groove_from_string(groove)
  if g then st.swing, st.h_t, st.h_v = g.swing, g.h_t, g.h_v end
  st.use_fill = (fill == "1")

  autosave_written = payload
  return true
end

-------------------------------------------------------------------------------
-- Writing the pattern to REAPER
-------------------------------------------------------------------------------

-- Auto-fill. It takes over the second half of this bar, and is offered only
-- once the pattern is at least that long. Change the bar number here alone.
local FILL_BAR   = 8
local FILL_START = (FILL_BAR - 1) * 16 + 9
local FILL_END   = FILL_BAR * 16

local function write_to_reaper(state)
  local track, src = target_track()
  if not track then
    return false, "No track selected, and none remembered in this project yet."
  end

  local start_pos = reaper.GetCursorPosition()
  local qn_offset = reaper.TimeMap2_timeToQN(0, start_pos)
  local end_time  = reaper.TimeMap2_QNToTime(0, qn_offset + (state.bars * 4))

  reaper.Undo_BeginBlock()

  -- Clear the way: selected items, plus patterns written here that overlap the
  -- new one. Moving the edit cursor elsewhere therefore lays a second pattern
  -- further along instead of wiping the first.
  for i = reaper.CountTrackMediaItems(track) - 1, 0, -1 do
    local item = reaper.GetTrackMediaItem(track, i)
    local drop = reaper.IsMediaItemSelected(item)
    if not drop then
      local _, tag = reaper.GetSetMediaItemInfo_String(item, ITEM_TAG, "", false)
      if tag == "1" then
        local p = reaper.GetMediaItemInfo_Value(item, "D_POSITION")
        local l = reaper.GetMediaItemInfo_Value(item, "D_LENGTH")
        if p < end_time and (p + l) > start_pos then drop = true end
      end
    end
    if drop then reaper.DeleteTrackMediaItem(track, item) end
  end

  local item = reaper.CreateNewMIDIItemInProj(track, start_pos, end_time, false)
  reaper.GetSetMediaItemInfo_String(item, ITEM_TAG, "1", true)
  reaper.SetMediaItemSelected(item, true)
  local take = reaper.GetActiveTake(item)
  reaper.MIDI_DisableSort(take)

  for i = 1, #DRUM_MAP do
    local inst = DRUM_MAP[i]
    for s = 1, state.bars * 16 do
      local layer = to_layer(grid[i][s])

      -- Auto-fill takes over the second half of the fill bar
      if state.use_fill and state.bars >= FILL_BAR
         and s >= FILL_START and s <= FILL_END then
        layer = 0
        if inst.id == "snare"   or inst.id == "tom_high"
        or inst.id == "tom_low" or inst.id == "rimshot" then
          if math.random() > 0.65 then
            layer = math.min(5, 2 + math.floor((s - (FILL_START - 1)) / 2))
          end
        end
        if s == FILL_END then
          if     inst.id == "kick"       then layer = 5
          elseif inst.id == "snare"
              or inst.id == "hihat_open" then
            layer = math.random() > 0.5 and 5 or 4
          end
        end
      end

      if layer > 0 then
        local pos_qn = (s - 1) * 0.25
        if s % 2 == 0 then
          pos_qn = pos_qn + ((state.swing / 100) * 0.083)
        end
        local ppq = math.floor(pos_qn * 960) + math.random(-state.h_t, state.h_t)
        local vel = vel_from_layer(layer, state.h_v)
        if inst.id == "hihat_closed" and layer <= 2 then
          vel = math.max(1, vel - 10)
        end
        reaper.MIDI_InsertNote(take, false, false, ppq, ppq + 120, 0,
          inst.note, vel, true)
      end
    end
  end
  reaper.MIDI_Sort(take)
  remember_track(track)
  reaper.Undo_EndBlock("SK Drums Generator: generate pattern", -1)
  reaper.UpdateArrange()

  return true, ("Written to \"%s\"%s."):format(
    track_name(track), (src == "memory") and "  (remembered track)" or "")
end

-------------------------------------------------------------------------------
-- Transport and note preview
--
--  PREVIEW sets the target track to All MIDI Inputs, arms it and turns input
--  monitoring on. The note buttons in the mapping panel then play through
--  whatever sampler sits on that track. Toggling PREVIEW off puts the track
--  back exactly as it was found.
-------------------------------------------------------------------------------

local REC_INPUT_ALL_MIDI = 4096 | (63 << 5) | 0  -- All MIDI Inputs, all channels

local PREVIEW_VEL = 100    -- velocity used when auditioning a note
local PREVIEW_LEN = 0.30   -- how long an auditioned note is held, in seconds

local pending_notes = {}

-- Plays a note now and queues its release, so a sustaining sampler
-- does not hang on it.
local function preview_note(note)
  if not note or note < 0 or note > 127 then return end
  reaper.StuffMIDIMessage(0, 0x90, note, PREVIEW_VEL)  -- note-on, channel 1
  pending_notes[#pending_notes + 1] = {
    note = note, deadline = reaper.time_precise() + PREVIEW_LEN }
end

local function flush_pending_notes(force)
  local now = reaper.time_precise()
  for i = #pending_notes, 1, -1 do
    if force or now >= pending_notes[i].deadline then
      reaper.StuffMIDIMessage(0, 0x80, pending_notes[i].note, 0)  -- note-off
      table.remove(pending_notes, i)
    end
  end
end

-- Remembers the track PREVIEW touched, and its settings from before.
local preview = { on = false, track = nil, rec_input = nil, rec_arm = nil, rec_mon = nil }

local function preview_off()
  local tr = preview.track
  if tr and reaper.ValidatePtr(tr, "MediaTrack*") then
    if preview.rec_input then reaper.SetMediaTrackInfo_Value(tr, "I_RECINPUT", preview.rec_input) end
    if preview.rec_arm   then reaper.SetMediaTrackInfo_Value(tr, "I_RECARM",   preview.rec_arm)   end
    if preview.rec_mon   then reaper.SetMediaTrackInfo_Value(tr, "I_RECMON",   preview.rec_mon)   end
  end
  flush_pending_notes(true)
  preview.on, preview.track = false, nil
  preview.rec_input, preview.rec_arm, preview.rec_mon = nil, nil, nil
end

local function preview_on()
  local tr, src = target_track()
  if not tr then return false, "No track selected, and none remembered in this project yet." end
  preview.track     = tr
  preview.rec_input = reaper.GetMediaTrackInfo_Value(tr, "I_RECINPUT")
  preview.rec_arm   = reaper.GetMediaTrackInfo_Value(tr, "I_RECARM")
  preview.rec_mon   = reaper.GetMediaTrackInfo_Value(tr, "I_RECMON")
  reaper.SetMediaTrackInfo_Value(tr, "I_RECINPUT", REC_INPUT_ALL_MIDI)
  reaper.SetMediaTrackInfo_Value(tr, "I_RECARM",   1)
  reaper.SetMediaTrackInfo_Value(tr, "I_RECMON",   1)  -- needed to hear the track's FX
  preview.on = true
  return true, ("Track armed: \"%s\" on All MIDI Inputs%s."):format(
    track_name(tr), (src == "memory") and "  (remembered track)" or "")
end

-- Drop the preview if its track has been deleted in the meantime.
local function preview_validate()
  if preview.on and (not preview.track
     or not reaper.ValidatePtr(preview.track, "MediaTrack*")) then
    preview.on, preview.track = false, nil
  end
end

local function is_playing() return (reaper.GetPlayState() & 1) == 1 end

local function transport_toggle()
  if is_playing() then reaper.CSurf_OnStop() else reaper.CSurf_OnPlay() end
end

local BPM_MIN, BPM_MAX = 1.0, 960.0

local function set_bpm(v)
  v = tonumber(v)
  if not v then return end
  reaper.SetCurrentBPM(0, math.max(BPM_MIN, math.min(BPM_MAX, v)), true)
end

-------------------------------------------------------------------------------
-- Interface
-------------------------------------------------------------------------------

local NOTE_NAMES = {"C","C#","D","D#","E","F","F#","G","G#","A","A#","B"}
local function note_to_name(n)
  if n < 0 or n > 127 then return "?" end
  return NOTE_NAMES[(n % 12) + 1] .. tostring(math.floor(n / 12) - 2)
end

local ctx = reaper.ImGui_CreateContext("Studio Kozak Drums Generator")

-------------------------------------------------------------------------------
-- Look and feel: dark background, amber accent.
-------------------------------------------------------------------------------

local FONT_TITLE = 22
local FONT_BTN   = 17
local fontTitle  = reaper.ImGui_CreateFont('sans-serif', FONT_TITLE)
local fontBtn    = reaper.ImGui_CreateFont('sans-serif', FONT_BTN)
reaper.ImGui_Attach(ctx, fontTitle)
reaper.ImGui_Attach(ctx, fontBtn)

-- Works with either ReaImGui font signature.
local _pfMode
local function PushFont(f, size)
  if _pfMode == 1 then
    reaper.ImGui_PushFont(ctx, f, size)
  elseif _pfMode == 2 then
    reaper.ImGui_PushFont(ctx, f)
  else
    if pcall(reaper.ImGui_PushFont, ctx, f, size) then _pfMode = 1
    else reaper.ImGui_PushFont(ctx, f); _pfMode = 2 end
  end
end
local function PopFont() reaper.ImGui_PopFont(ctx) end

local COL_ACCENT   = 0xD9A441FF
local COL_ACCENT_H = 0xE6B75AFF
local COL_ACCENT_A = 0xB8863BFF
local COL_INK      = 0x181A1FFF
local COL_PAPER    = 0xE9E5DAFF

-- Grid lines. Raise or lower these two if the grid reads too loud or too faint.
local COL_GRID_STRONG = 0xE9E5DAFF   -- outer frame and header
local COL_GRID_LIGHT  = 0xB0AB9DFF   -- lines between cells

-- Empty steps
local COL_CELL_OFF     = 0x212429FF
local COL_CELL_OFF_ACC = 0x2A2D33FF  -- columns falling on a beat

local THEME_COLORS = {
  { reaper.ImGui_Col_WindowBg(),        0x1E2024FF },
  { reaper.ImGui_Col_PopupBg(),         0x24272CFF },
  { reaper.ImGui_Col_Text(),            0xE9E5DAFF },
  { reaper.ImGui_Col_TextDisabled(),    0x8C8778FF },
  { reaper.ImGui_Col_FrameBg(),         0x2A2D33FF },
  { reaper.ImGui_Col_FrameBgHovered(),  0x353942FF },
  { reaper.ImGui_Col_FrameBgActive(),   0x3E434DFF },
  { reaper.ImGui_Col_Button(),          0x30343BFF },
  { reaper.ImGui_Col_ButtonHovered(),   0x3B404AFF },
  { reaper.ImGui_Col_ButtonActive(),    0x474D58FF },
  { reaper.ImGui_Col_CheckMark(),       COL_ACCENT },
  { reaper.ImGui_Col_Header(),          0x33373FFF },
  { reaper.ImGui_Col_HeaderHovered(),   0x3F444EFF },
  { reaper.ImGui_Col_HeaderActive(),    0x4A505BFF },
  { reaper.ImGui_Col_Separator(),       0x3A3E46FF },
  { reaper.ImGui_Col_Border(),          0x35393FFF },
  { reaper.ImGui_Col_TitleBg(),         0x181A1EFF },
  { reaper.ImGui_Col_TitleBgActive(),   0x24272CFF },
  { reaper.ImGui_Col_SliderGrab(),        COL_ACCENT   },
  { reaper.ImGui_Col_SliderGrabActive(),  COL_ACCENT_H },
  { reaper.ImGui_Col_TableBorderStrong(), COL_GRID_STRONG },
  { reaper.ImGui_Col_TableBorderLight(),  COL_GRID_LIGHT  },
  { reaper.ImGui_Col_TableRowBg(),        0x00000000 },
  { reaper.ImGui_Col_TableRowBgAlt(),     0xFFFFFF07 },
}

local function pushTheme()
  for _, c in ipairs(THEME_COLORS) do reaper.ImGui_PushStyleColor(ctx, c[1], c[2]) end
  reaper.ImGui_PushStyleVar(ctx, reaper.ImGui_StyleVar_WindowRounding(),  8)
  reaper.ImGui_PushStyleVar(ctx, reaper.ImGui_StyleVar_FrameRounding(),   6)
  reaper.ImGui_PushStyleVar(ctx, reaper.ImGui_StyleVar_GrabRounding(),    6)
  reaper.ImGui_PushStyleVar(ctx, reaper.ImGui_StyleVar_PopupRounding(),   6)
  reaper.ImGui_PushStyleVar(ctx, reaper.ImGui_StyleVar_WindowPadding(),   18, 12)
  reaper.ImGui_PushStyleVar(ctx, reaper.ImGui_StyleVar_FramePadding(),    10, 5)
  reaper.ImGui_PushStyleVar(ctx, reaper.ImGui_StyleVar_ItemSpacing(),     10, 6)
end
local N_VARS = 7
local function popTheme()
  reaper.ImGui_PopStyleVar(ctx, N_VARS)
  reaper.ImGui_PopStyleColor(ctx, #THEME_COLORS)
end

local function sectionLabel(txt)
  reaper.ImGui_TextDisabled(ctx, txt)
end

-- The main action button: amber, dark text.
local function accentButton(label, width, height)
  reaper.ImGui_PushStyleColor(ctx, reaper.ImGui_Col_Button(),        COL_ACCENT)
  reaper.ImGui_PushStyleColor(ctx, reaper.ImGui_Col_ButtonHovered(), COL_ACCENT_H)
  reaper.ImGui_PushStyleColor(ctx, reaper.ImGui_Col_ButtonActive(),  COL_ACCENT_A)
  reaper.ImGui_PushStyleColor(ctx, reaper.ImGui_Col_Text(),          COL_INK)
  reaper.ImGui_PushStyleVar(ctx, reaper.ImGui_StyleVar_FramePadding(), 12, 5)
  local pressed = reaper.ImGui_Button(ctx, label, width, height)
  reaper.ImGui_PopStyleVar(ctx)
  reaper.ImGui_PopStyleColor(ctx, 4)
  return pressed
end

-- Picks dark or light text, whichever stays readable on the given background.
local function textOn(rgba)
  local r = (rgba >> 24) & 0xFF
  local g = (rgba >> 16) & 0xFF
  local b = (rgba >>  8) & 0xFF
  local brightness = (0.299 * r + 0.587 * g + 0.114 * b) / 255
  return (brightness > 0.55) and COL_INK or COL_PAPER
end

-- Brightens or darkens a colour, keeping its transparency.
local function shade(rgba, f)
  local r = math.min(255, math.floor(((rgba >> 24) & 0xFF) * f))
  local g = math.min(255, math.floor(((rgba >> 16) & 0xFF) * f))
  local b = math.min(255, math.floor(((rgba >>  8) & 0xFF) * f))
  return (r << 24) | (g << 16) | (b << 8) | (rgba & 0xFF)
end

-- The small coloured dot identifying a drum element.
local function colorDot(rgba, radius, h)
  radius = radius or 4
  local dl   = reaper.ImGui_GetWindowDrawList(ctx)
  local x, y = reaper.ImGui_GetCursorScreenPos(ctx)
  h = h or reaper.ImGui_GetTextLineHeight(ctx)
  reaper.ImGui_DrawList_AddCircleFilled(dl, x + radius, y + h * 0.5, radius, rgba)
  reaper.ImGui_Dummy(ctx, radius * 2, h)
end

-- A square button holding a drawn symbol: 'play', 'stop' or 'circle'.
-- When active it turns amber.
local function iconButton(id, kind, size, active)
  local x, y    = reaper.ImGui_GetCursorScreenPos(ctx)
  local clicked = reaper.ImGui_InvisibleButton(ctx, id, size, size)
  local hovered = reaper.ImGui_IsItemHovered(ctx)
  local held    = reaper.ImGui_IsItemActive(ctx)
  local dl      = reaper.ImGui_GetWindowDrawList(ctx)

  local bg
  if active then
    bg = held and COL_ACCENT_A or (hovered and COL_ACCENT_H or COL_ACCENT)
  else
    bg = held and 0x474D58FF or (hovered and 0x3B404AFF or 0x30343BFF)
  end
  reaper.ImGui_DrawList_AddRectFilled(dl, x, y, x + size, y + size, bg, 6)

  local fg     = active and COL_INK or COL_PAPER
  local cx, cy = x + size * 0.5, y + size * 0.5
  local r      = size * 0.26

  if kind == 'play' then
    -- Sitting slightly right: a triangle looks off-centre when truly centred.
    reaper.ImGui_DrawList_AddTriangleFilled(dl,
      cx - r * 0.70, cy - r,
      cx - r * 0.70, cy + r,
      cx + r * 0.95, cy, fg)
  elseif kind == 'stop' then
    local h = r * 0.78
    reaper.ImGui_DrawList_AddRectFilled(dl, cx - h, cy - h, cx + h, cy + h, fg, 1)
  else -- 'circle'
    reaper.ImGui_DrawList_AddCircleFilled(dl, cx, cy, r * 0.85, fg)
  end

  return clicked
end

-- Shortest gap between two velocity steps made with the wheel. Lower it if the
-- wheel feels sluggish, raise it if one notch moves more than one layer.
local WHEEL_STEP_GAP = 0.08

local state = {
  bars            = 1,
  h_t             = 0,   -- timing spread, in MIDI ticks (0 = dead on the grid)
  h_v             = 0,   -- velocity spread around the layer range (0 = exact)
  swing           = 0,
  current_page    = 0,
  use_fill        = false,
  selected_factory = 1,  -- 0 when a user pattern is loaded instead
  selected_user    = 0,  -- 0 when none is selected
  vel_edit_mode   = false,
}

local _  -- throwaway for the returns we ignore

local ui_save_name     = ""
local ui_save_msg      = ""
local ui_save_msg_time = 0
local ui_clipboard_msg = ""
local ui_clipboard_time = 0
local ui_export_name   = ""
local ui_edit_name     = nil           -- drum element being renamed on the grid
local ui_edit_focus    = false
local ui_status        = ""
local ui_status_time   = 0
local ui_bpm           = nil
local ui_wheel_time    = 0     -- when the wheel last moved a layer
local ui_wheel_cell    = nil   -- which step it moved

local note_inputs = {}
for i, inst in ipairs(DRUM_MAP) do note_inputs[i] = inst.note end

init_grid(16, true)

-- Pick the pattern back up where it was left in this project. When there is
-- nothing to restore, remember the empty pattern as-is so that opening the
-- script and closing it again writes nothing.
if not autoload(state) then
  autosave_written = state_to_string(state)
end

-- Shows a message for three seconds.
local function feedback(msg, is_clipboard)
  if is_clipboard then
    ui_clipboard_msg  = msg
    ui_clipboard_time = reaper.time_precise()
  else
    ui_save_msg       = msg
    ui_save_msg_time  = reaper.time_precise()
  end
end

local first_frame = true

local function loop()
  flush_pending_notes(false)
  preview_validate()
  autosave(state)

  -- Pick up the saved notes on the first frame, before the fields can report a
  -- change that never happened.
  if first_frame then
    for i, inst in ipairs(DRUM_MAP) do note_inputs[i] = inst.note end
    first_frame = false
  end

  -- Let timed messages expire
  if ui_save_msg ~= "" and reaper.time_precise() - ui_save_msg_time > 3 then
    ui_save_msg = ""
  end
  if ui_clipboard_msg ~= "" and reaper.time_precise() - ui_clipboard_time > 3 then
    ui_clipboard_msg = ""
  end
  if ui_status ~= "" and reaper.time_precise() - ui_status_time > 3 then
    ui_status = ""
  end

  pushTheme()
  reaper.ImGui_SetNextWindowSize(ctx, 680, 900, reaper.ImGui_Cond_FirstUseEver())
  local visible, open = reaper.ImGui_Begin(ctx,
    "SK Drums Generator",
    true, reaper.ImGui_WindowFlags_AlwaysAutoResize())

  if visible then

    -- Title
    PushFont(fontTitle, FONT_TITLE)
    reaper.ImGui_PushStyleColor(ctx, reaper.ImGui_Col_Text(), COL_ACCENT)
    reaper.ImGui_Text(ctx, "SK DRUMS GENERATOR")
    reaper.ImGui_PopStyleColor(ctx)
    PopFont()
    reaper.ImGui_Separator(ctx)

    -- Bars, pattern tools and session tempo
    reaper.ImGui_SetNextItemWidth(ctx, 110)
    local chg, nb = reaper.ImGui_InputInt(ctx, "Bars", state.bars)
    if chg and nb > 0 then
      state.bars = nb
      init_grid(state.bars * 16, false)
    end

    reaper.ImGui_SameLine(ctx)
    if reaper.ImGui_Button(ctx, "DUPLICATE") then
      local old  = state.bars
      state.bars = old * 2
      init_grid(state.bars * 16, false)
      for i = 1, #DRUM_MAP do
        for s = 1, old * 16 do
          grid[i][s + (old * 16)] = grid[i][s]
        end
      end
    end

    reaper.ImGui_SameLine(ctx)
    if reaper.ImGui_Button(ctx, "RESET") then init_grid(state.bars * 16, true) end

    reaper.ImGui_SameLine(ctx)
    if reaper.ImGui_Button(ctx, "RANDOM") then
      randomize_intelligent(state.current_page, state.current_page)
    end

    -- The tempo field follows REAPER unless you are typing in it.
    reaper.ImGui_SameLine(ctx, 0, 24)
    reaper.ImGui_TextDisabled(ctx, "BPM")
    reaper.ImGui_SameLine(ctx, 0, 6)

    local bpm_live = reaper.Master_GetTempo()
    if ui_bpm == nil then ui_bpm = bpm_live end

    reaper.ImGui_SetNextItemWidth(ctx, 78)
    local bchg, bval = reaper.ImGui_InputDouble(ctx, "##bpm", ui_bpm, 0, 0, "%.2f")
    if bchg then ui_bpm = bval end
    -- Applied on Enter or when the field is left, never mid-typing.
    if reaper.ImGui_IsItemDeactivatedAfterEdit(ctx) then
      set_bpm(ui_bpm)
      ui_bpm = reaper.Master_GetTempo()
    elseif not reaper.ImGui_IsItemActive(ctx) then
      ui_bpm = bpm_live
    end

    reaper.ImGui_SameLine(ctx, 0, 4)
    if reaper.ImGui_Button(ctx, "-##bpmdn", 26, 0) then
      set_bpm(bpm_live - 1)
      ui_bpm = reaper.Master_GetTempo()
    end
    reaper.ImGui_SameLine(ctx, 0, 4)
    if reaper.ImGui_Button(ctx, "+##bpmup", 26, 0) then
      set_bpm(bpm_live + 1)
      ui_bpm = reaper.Master_GetTempo()
    end

    reaper.ImGui_Separator(ctx)

    -- Factory patterns
    sectionLabel("FACTORY PRESETS")
    reaper.ImGui_SetNextItemWidth(ctx, 300)
    local factory_label = state.selected_factory > 0
      and FACTORY_PRESETS[state.selected_factory].name
      or  "-- user preset active --"
    if reaper.ImGui_BeginCombo(ctx, "##factory", factory_label) then
      for i, p in ipairs(FACTORY_PRESETS) do
        if reaper.ImGui_Selectable(ctx, p.name, i == state.selected_factory) then
          state.selected_factory = i
          state.selected_user    = 0
          p.func(state.bars * 16)
          if p.groove then
            state.swing = p.groove.swing
            state.h_t   = p.groove.h_t
            state.h_v   = p.groove.h_v
          end
        end
      end
      reaper.ImGui_EndCombo(ctx)
    end

    -- Your own patterns

    local user_header_label = #user_presets == 0
      and "USER PRESETS  (none saved)"
      or  "USER PRESETS  (" .. #user_presets .. " saved)"

    if reaper.ImGui_CollapsingHeader(ctx, user_header_label) then

      reaper.ImGui_Spacing(ctx)

      if #user_presets == 0 then
        reaper.ImGui_TextDisabled(ctx, "  No user presets saved yet.")
      else
        reaper.ImGui_SetNextItemWidth(ctx, 300)
        local user_label = state.selected_user > 0
          and user_presets[state.selected_user].name
          or  "-- select a user preset --"
        if reaper.ImGui_BeginCombo(ctx, "##user", user_label) then
          for i, p in ipairs(user_presets) do
            local is_sel = (i == state.selected_user)
            if reaper.ImGui_Selectable(ctx, p.name, is_sel) then
              state.selected_user    = i
              state.selected_factory = 0
            end
          end
          reaper.ImGui_EndCombo(ctx)
        end

        reaper.ImGui_SameLine(ctx)
        if reaper.ImGui_Button(ctx, "LOAD") then
          if state.selected_user > 0 then
            local p = user_presets[state.selected_user]
            state.bars = p.bars
            init_grid(p.bars * 16, true)
            p.func(p.bars * 16)
            -- A pattern with no groove stored leaves the sliders alone.
            if p.groove then
              state.swing = p.groove.swing
              state.h_t   = p.groove.h_t
              state.h_v   = p.groove.h_v
            end
            feedback("Loaded: " .. p.name)
          end
        end

        reaper.ImGui_SameLine(ctx)
        reaper.ImGui_PushStyleColor(ctx, reaper.ImGui_Col_Button(), 0x882222FF)
        if reaper.ImGui_Button(ctx, "DELETE") then
          if state.selected_user > 0 then
            local name = user_presets[state.selected_user].name
            delete_user_preset(state.selected_user)
            state.selected_user = 0
            feedback("Deleted: " .. name)
          end
        end
        reaper.ImGui_PopStyleColor(ctx)
      end

      if ui_save_msg ~= "" then
        reaper.ImGui_SameLine(ctx)
        reaper.ImGui_TextColored(ctx, 0x88FF88FF, ui_save_msg)
      end

      reaper.ImGui_Separator(ctx)

      reaper.ImGui_Text(ctx, "Save current pattern as user preset :")
      reaper.ImGui_SetNextItemWidth(ctx, 220)
      _, ui_save_name = reaper.ImGui_InputText(ctx, "##savename", ui_save_name)
      reaper.ImGui_SameLine(ctx)
      reaper.ImGui_PushStyleColor(ctx, reaper.ImGui_Col_Button(), 0x226622FF)
      if reaper.ImGui_Button(ctx, "SAVE PRESET") then
        local ok, msg = save_current_as_user_preset(ui_save_name, state.bars,
          { swing = state.swing, h_t = state.h_t, h_v = state.h_v })
        feedback(msg)
        if ok then ui_save_name = "" end
      end
      reaper.ImGui_PopStyleColor(ctx)

      reaper.ImGui_Separator(ctx)

      reaper.ImGui_Text(ctx, "Export to clipboard (paste into script source) :")
      reaper.ImGui_SetNextItemWidth(ctx, 220)
      _, ui_export_name = reaper.ImGui_InputText(ctx, "##exportname", ui_export_name)
      reaper.ImGui_SameLine(ctx)
      reaper.ImGui_PushStyleColor(ctx, reaper.ImGui_Col_Button(), 0x225566FF)
      if reaper.ImGui_Button(ctx, "COPY LUA CODE") then
        local ok, err = export_to_clipboard(ui_export_name, state.bars,
          { swing = state.swing, h_t = state.h_t, h_v = state.h_v })
        feedback(ok and "Lua code copied to clipboard!" or err, true)
      end
      reaper.ImGui_PopStyleColor(ctx)

      if ui_clipboard_msg ~= "" then
        reaper.ImGui_SameLine(ctx)
        reaper.ImGui_TextColored(ctx, 0xFFDD44FF, ui_clipboard_msg)
      end

      reaper.ImGui_TextDisabled(ctx,
        "  Paste the copied code inside FACTORY_PRESETS in the script source.")

      reaper.ImGui_Spacing(ctx)

    end  -- end CollapsingHeader USER PRESETS

    -- Note and name assignment

    if reaper.ImGui_CollapsingHeader(ctx,
        "MIDI MAPPING##midi_mapping") then

      reaper.ImGui_Spacing(ctx)

      -- ARM button, sized to the height of the text buttons beside it so the
      -- row lines up. Amber when the track is armed, grey when not. Arming
      -- routes All MIDI Inputs to the target track, so the note buttons below
      -- play through its sampler.
      local arm_h = reaper.ImGui_GetFrameHeight(ctx)
      if iconButton("##arm", 'circle', arm_h, preview.on) then
        if preview.on then
          preview_off()
          ui_status = "Track disarmed, restored."
        else
          local ok, msg = preview_on()
          ui_status = msg
        end
        ui_status_time = reaper.time_precise()
      end
      reaper.ImGui_SameLine(ctx)

      reaper.ImGui_PushStyleColor(ctx, reaper.ImGui_Col_Button(), 0x226622FF)
      if reaper.ImGui_Button(ctx, "SAVE MAPPING") then
        save_mapping()
      end
      reaper.ImGui_PopStyleColor(ctx)
      reaper.ImGui_SameLine(ctx)

      reaper.ImGui_PushStyleColor(ctx, reaper.ImGui_Col_Button(), 0x884400FF)
      if reaper.ImGui_Button(ctx, "RESET MAPPING") then
        reset_mapping()
        for i, inst in ipairs(DRUM_MAP) do note_inputs[i] = inst.note end
      end
      reaper.ImGui_PopStyleColor(ctx)
      reaper.ImGui_SameLine(ctx)
      reaper.ImGui_TextDisabled(ctx, "arm the track, then click a note to hear it")

      reaper.ImGui_Spacing(ctx)

      reaper.ImGui_Spacing(ctx)
      reaper.ImGui_TextDisabled(ctx,
        "  Rename freely. Click a note name to audition it through the track's FX.")
      reaper.ImGui_Spacing(ctx)

      local cols_per_row = 2
      for i, inst in ipairs(DRUM_MAP) do
        if (i - 1) % cols_per_row ~= 0 then reaper.ImGui_SameLine(ctx, 0, 20) end
        reaper.ImGui_PushID(ctx, 9000 + i)
        reaper.ImGui_BeginGroup(ctx)

        colorDot(inst.color, 5, reaper.ImGui_GetFrameHeight(ctx))
        reaper.ImGui_SameLine(ctx, 0, 6)

        -- Renaming here also renames the element on the grid
        reaper.ImGui_SetNextItemWidth(ctx, 90)
        local _, nval = reaper.ImGui_InputText(ctx, "##name", inst.name)
        if nval ~= inst.name then DRUM_MAP[i].name = nval:sub(1, NAME_MAX) end
        if reaper.ImGui_IsItemDeactivatedAfterEdit(ctx) then
          DRUM_MAP[i].name = sanitize_name(DRUM_MAP[i].name) or DEFAULT_NAMES[i]
        end
        reaper.ImGui_SameLine(ctx, 0, 6)

        reaper.ImGui_SetNextItemWidth(ctx, 92)
        local changed, new_val = reaper.ImGui_InputInt(ctx, "##note", note_inputs[i])
        if changed then
          new_val          = math.max(0, math.min(127, new_val))
          note_inputs[i]   = new_val
          DRUM_MAP[i].note = new_val
        end
        reaper.ImGui_SameLine(ctx, 0, 6)

        -- Plays the note through the track's sampler
        if reaper.ImGui_Button(ctx, note_to_name(note_inputs[i]), 48, 0) then
          preview_note(note_inputs[i])
          if not preview.on then
            ui_status      = "Arm the track first (round button) to hear the note."
            ui_status_time = reaper.time_precise()
          end
        end

        reaper.ImGui_EndGroup(ctx)
        reaper.ImGui_PopID(ctx)
      end

      reaper.ImGui_Spacing(ctx)

    end  -- end CollapsingHeader MIDI MAPPING

    -- Velocity mode and auto-fill
    if state.vel_edit_mode then
      if accentButton("VELOCITY MODE  [ON]", 190, 0) then
        state.vel_edit_mode = false
      end
    else
      if reaper.ImGui_Button(ctx, "VELOCITY MODE [OFF]", 190, 0) then
        state.vel_edit_mode = true
      end
    end

    reaper.ImGui_SameLine(ctx)
    local can_fill = state.bars >= FILL_BAR
    if not can_fill then reaper.ImGui_BeginDisabled(ctx) end
    _, state.use_fill = reaper.ImGui_Checkbox(ctx, "AUTO-FILL BAR " .. FILL_BAR, state.use_fill)
    if not can_fill then reaper.ImGui_EndDisabled(ctx) end

    reaper.ImGui_SameLine(ctx)
    reaper.ImGui_TextDisabled(ctx,
      state.vel_edit_mode
        and "mouse wheel over a step sets its velocity"
        or "click = on/off")

    reaper.ImGui_Separator(ctx)

    -- One button per bar
    for p = 0, state.bars - 1 do
      if p > 0 and p % 8 ~= 0 then reaper.ImGui_SameLine(ctx) end
      local is_sel = (state.current_page == p)
      if is_sel then
        reaper.ImGui_PushStyleColor(ctx, reaper.ImGui_Col_Button(), COL_ACCENT)
        reaper.ImGui_PushStyleColor(ctx, reaper.ImGui_Col_Text(),   COL_INK)
      end
      if reaper.ImGui_Button(ctx, tostring(p + 1), 35, 25) then
        state.current_page = p
      end
      if is_sel then reaper.ImGui_PopStyleColor(ctx, 2) end
    end

    -- The step grid
    -- Widen the left column if an element has been given a long name.
    local inst_col_w = 84
    for _, inst in ipairs(DRUM_MAP) do
      local tw = reaper.ImGui_CalcTextSize(ctx, inst.name)
      if tw + 30 > inst_col_w then inst_col_w = tw + 30 end
    end

    if reaper.ImGui_BeginTable(ctx, "grid", 17,
        reaper.ImGui_TableFlags_Borders() | reaper.ImGui_TableFlags_RowBg()) then
      reaper.ImGui_TableSetupColumn(ctx, "INST",
        reaper.ImGui_TableColumnFlags_WidthFixed(), inst_col_w)
      for s = 1, 16 do
        reaper.ImGui_TableSetupColumn(ctx, "",
          reaper.ImGui_TableColumnFlags_WidthFixed(), 25)
      end

      reaper.ImGui_TableNextRow(ctx)
      reaper.ImGui_TableSetColumnIndex(ctx, 0)
      reaper.ImGui_Text(ctx, "BEAT")
      for s = 1, 16 do
        reaper.ImGui_TableSetColumnIndex(ctx, s)
        if s % 4 == 1 then reaper.ImGui_TextColored(ctx, COL_ACCENT, "|")
        else reaper.ImGui_Text(ctx, ".") end
      end

      for i = 1, #DRUM_MAP do
        reaper.ImGui_TableNextRow(ctx)
        reaper.ImGui_TableSetColumnIndex(ctx, 0)
        if ui_edit_name == i then
          -- Renaming here also renames the element in the mapping panel.
          reaper.ImGui_PushID(ctx, 7000 + i)
          if ui_edit_focus then
            reaper.ImGui_SetKeyboardFocusHere(ctx)
            ui_edit_focus = false
          end
          reaper.ImGui_SetNextItemWidth(ctx, inst_col_w - 6)
          local entered, v = reaper.ImGui_InputText(ctx, "##gridname", DRUM_MAP[i].name,
              reaper.ImGui_InputTextFlags_EnterReturnsTrue()
            | reaper.ImGui_InputTextFlags_AutoSelectAll())
          DRUM_MAP[i].name = v:sub(1, NAME_MAX)
          if entered or reaper.ImGui_IsItemDeactivated(ctx) then
            DRUM_MAP[i].name = sanitize_name(DRUM_MAP[i].name) or DEFAULT_NAMES[i]
            save_mapping()
            ui_edit_name = nil
          end
          reaper.ImGui_PopID(ctx)
        else
          colorDot(DRUM_MAP[i].color)
          reaper.ImGui_SameLine(ctx, 0, 5)
          reaper.ImGui_Text(ctx, DRUM_MAP[i].name)
          if reaper.ImGui_IsItemHovered(ctx)
             and reaper.ImGui_IsMouseDoubleClicked(ctx, reaper.ImGui_MouseButton_Left()) then
            ui_edit_name  = i
            ui_edit_focus = true
          end
        end

        for s = 1, 16 do
          local step  = (state.current_page * 16) + s
          local layer = to_layer(grid[i][step])
          reaper.ImGui_TableSetColumnIndex(ctx, s)
          reaper.ImGui_PushID(ctx, (i * 100000) + step)

          -- Cell colour follows the velocity layer, matching the legend.
          local btn_col, txt_col
          if layer == 0 then
            btn_col = (s % 4 == 1) and COL_CELL_OFF_ACC or COL_CELL_OFF
            txt_col = COL_PAPER
          else
            btn_col = VEL_COLORS[layer]
            txt_col = textOn(btn_col)
          end

          reaper.ImGui_PushStyleColor(ctx, reaper.ImGui_Col_Button(),        btn_col)
          reaper.ImGui_PushStyleColor(ctx, reaper.ImGui_Col_ButtonHovered(), shade(btn_col, 1.30))
          reaper.ImGui_PushStyleColor(ctx, reaper.ImGui_Col_ButtonActive(),  shade(btn_col, 0.80))
          reaper.ImGui_PushStyleColor(ctx, reaper.ImGui_Col_Text(),          txt_col)
          local label = (layer > 0) and (tostring(layer) .. "##b") or "##c"
            if reaper.ImGui_Button(ctx, label, 25, 25) then
               if state.vel_edit_mode then
              grid[i][step] = (layer + 1) % 6
              else
               grid[i][step] = (layer == 0) and 3 or 0
            end
          end
            if state.vel_edit_mode and reaper.ImGui_IsItemHovered(ctx) then
              local wheel = reaper.ImGui_GetMouseWheel(ctx)
              if wheel ~= 0 then
                -- Only the direction is used, never the amount. How much a
                -- wheel reports for one notch is not the same from one machine
                -- to the next, and a quick flick can report dozens of units at
                -- once, so reading the amount would make a step mean something
                -- different on every desk. Spacing steps out in time behaves
                -- the same everywhere: one notch moves one layer, and a flick
                -- moves one layer instead of slamming to the end.
                local cell = (i * 100000) + step
                local now  = reaper.time_precise()
                if ui_wheel_cell ~= cell
                   or (now - ui_wheel_time) >= WHEEL_STEP_GAP then
                  ui_wheel_cell, ui_wheel_time = cell, now
                  local dir = (wheel > 0) and 1 or -1
                  grid[i][step] = math.max(0, math.min(5, layer + dir))
                end
              end
            end
          reaper.ImGui_PopStyleColor(ctx, 4)
          reaper.ImGui_PopID(ctx)
        end
      end
      reaper.ImGui_EndTable(ctx)
    end

    -- Velocity legend
    reaper.ImGui_TextDisabled(ctx, "Layers : ")
    for i = 1, 5 do
      reaper.ImGui_SameLine(ctx)
      reaper.ImGui_TextColored(ctx, VEL_COLORS[i], i .. "-" .. VEL_LAYERS[i].label)
    end
    reaper.ImGui_NewLine(ctx)

    -- Groove
    sectionLabel("GROOVE & HUMANIZATION")
    reaper.ImGui_SetNextItemWidth(ctx, 130)
    _, state.swing = reaper.ImGui_SliderInt(ctx, "Swing",   state.swing, 0, 100)
    reaper.ImGui_SameLine(ctx)
    reaper.ImGui_SetNextItemWidth(ctx, 130)
    _, state.h_t   = reaper.ImGui_SliderInt(ctx, "Timing",  state.h_t,   0, 100)
    reaper.ImGui_SameLine(ctx)
    reaper.ImGui_SetNextItemWidth(ctx, 130)
    _, state.h_v   = reaper.ImGui_SliderInt(ctx, "Var.Vel", state.h_v,   0, 80)

    -- Transport, preview and generate
    reaper.ImGui_Dummy(ctx, 0, 8)

    local ACTION_H = 45

    -- Follows REAPER's transport, so it stays right if you use the spacebar.
    local playing = is_playing()
    if iconButton("##transport", playing and 'stop' or 'play', ACTION_H, playing) then
      transport_toggle()
    end
    reaper.ImGui_SameLine(ctx)

    PushFont(fontBtn, FONT_BTN)
    if accentButton("GENERATE & REPLACE", -1, ACTION_H) then
      local _, msg = write_to_reaper(state)
      ui_status      = msg
      ui_status_time = reaper.time_precise()
    end
    PopFont()

    -- Where the pattern will be written.
    local tt = target_track()
    if tt then
      reaper.ImGui_TextDisabled(ctx, "Target : " .. track_name(tt))
    else
      reaper.ImGui_TextDisabled(ctx,
        "Target : none  -  select a track in REAPER to generate.")
    end

    if ui_status ~= "" then
      reaper.ImGui_TextColored(ctx, COL_ACCENT, ui_status)
    end

    reaper.ImGui_End(ctx)
  end

  popTheme()

  if open then reaper.defer(loop) end
end

-- Leave nothing behind when the script closes: release any held note, hand the
-- track back as it was found, and store the pattern one last time so that a
-- window closed seconds after an edit still keeps it.
reaper.atexit(function()
  flush_pending_notes(true)
  if preview.on then preview_off() end
  autosave(state, true)
end)

reaper.defer(loop)
